### ISSUE TITLE
Check the correctness of DCB data GBTxs to Pathfinder COMET connectors mapping

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/COMET-DCB-Mapping#4]
@manuelfs I have release another debug mapping (see [1]) for DCB data GBTxs (`U[1-6]_IC2`) -> Pathfinder `COMET_{A,B}_J{1,2}`. Please help me check the correctness of the mapping (maybe with the help of some undergrads).

Now the only remaining task to generate a full COMET -> DCB mapping is to connect these 2 mappings together.

[1]: https://github.com/umd-lhcb/COMET-DCB-mapping/releases/tag/0.2

**Comment by jorger99** [comment]
After lots of arguing about even/odd/left/right, we have determined a rule for matching pins for J6:

**The even side of J6 on the COMET has Pin N corresponding to Pin N-1 on the DB’s J6.
The odd side of J6 on the COMET has Pin N corresponding to Pin N+1 on the DB’s J6**

There are also 6 pins that have their *net name* switched from N to P or vice versa which are located int the wiki.

**Comment by yipengsun** [comment]
Note that on the DCB -> Pathfinder side, we don't expect any pin-flipping shenanigans.

**Comment by yipengsun** [comment]
Also, you should update your findings at [1]. Please try to following the existing table format.


[1]: https://github.com/umd-lhcb/COMET-DCB-mapping/wiki/Manual-validation-of-COMET--DCB-connections

**Comment by yipengsun** [comment]
@LegyPlegy @SummerLeaves wonderful job. I didn't check it until now. Thanks a lot!
